import { pgTable, serial, varchar, text, decimal, timestamp, integer, boolean } from 'drizzle-orm/pg-core';

export const app_users = pgTable('app_users', {
  id: serial('id').primaryKey(),
  email: varchar('email', { length: 255 }).unique().notNull(),
  passwordHash: varchar('password_hash', { length: 255 }).notNull(),
  role: varchar('role', { length: 50 }).notNull().default('user'), // 'admin' or 'user'
  createdAt: timestamp('created_at').defaultNow(),
});

export const b4t_users = pgTable('b4t_users', {
  userId: integer('user_id').primaryKey(),
  firstName: varchar('first_name', { length: 100 }).notNull(),
  lastName: varchar('last_name', { length: 100 }).notNull(),
  email: varchar('email', { length: 255 }).unique().notNull(),
  billingRate: decimal('billing_rate', { precision: 10, scale: 2 }).default('0.00'),
  status: varchar('status', { length: 50 }).notNull().default('Active'),
  userType: varchar('user_type', { length: 100 }),
  employeeRoleId: integer('employee_role_id'),
  createdDate: timestamp('created_date'),
});

export const b4t_clients = pgTable('b4t_clients', {
  internalClientId: integer('internal_client_id').primaryKey(),
  clientId: varchar('client_id', { length: 50 }),
  clientName: varchar('client_name', { length: 255 }),
  clientPrefix: varchar('client_prefix', { length: 50 }),
  billingName: varchar('billing_name', { length: 255 }),
  clientType: varchar('client_type', { length: 100 }),
  creationDate: timestamp('creation_date'),
  accountManagerId: integer('account_manager_id'),
  accountManagerName: varchar('account_manager_name', { length: 255 }),
  clientStatus: varchar('client_status', { length: 50 }),
  address1: varchar('address1', { length: 255 }),
  address2: varchar('address2', { length: 255 }),
  address3: varchar('address3', { length: 255 }),
  city: varchar('city', { length: 100 }),
  state: varchar('state', { length: 50 }),
  country: varchar('country', { length: 100 }),
  postalCode: varchar('postal_code', { length: 20 }),
  phone: varchar('phone', { length: 50 }),
  mobile: varchar('mobile', { length: 50 }),
  fax: varchar('fax', { length: 50 }),
  email: varchar('email', { length: 255 }),
  primaryContactId: integer('primary_contact_id'),
  primaryContactFirstName: varchar('primary_contact_first_name', { length: 100 }),
  primaryContactLastName: varchar('primary_contact_last_name', { length: 100 }),
  currencyCode: varchar('currency_code', { length: 10 }),
  currencySymbol: varchar('currency_symbol', { length: 10 })
});

export const b4t_matters = pgTable('b4t_matters', {
  internalProjectId: integer('internal_project_id').primaryKey(),
  projectId: varchar('project_id', { length: 50 }),
  location: varchar('location', { length: 255 }),
  projectName: varchar('project_name', { length: 255 }),
  internalClientId: integer('internal_client_id'),
  clientName: varchar('client_name', { length: 255 }),
  status: varchar('status', { length: 50 }),
  projectType: varchar('project_type', { length: 100 }),
  description: text('description'),
  assignedToId: integer('assigned_to_id'),
  assignedToName: varchar('assigned_to_name', { length: 255 }),
  primaryProjectContactId: integer('primary_project_contact_id'),
  primaryProjectContactName: varchar('primary_project_contact_name', { length: 255 }),
  paymentDue: varchar('payment_due', { length: 50 }),
  createdDate: timestamp('created_date'),
  projectDueDate: timestamp('project_due_date'),
  closeDate: timestamp('close_date'),
  billingMethod: varchar('billing_method', { length: 50 }),
  hourlyRateType: varchar('hourly_rate_type', { length: 50 }),
  hourlyOverrideRate: decimal('hourly_override_rate', { precision: 10, scale: 2 }),
  percentRate: decimal('percent_rate', { precision: 5, scale: 2 }),
  flatFeeRate: decimal('flat_fee_rate', { precision: 10, scale: 2 }),
  defaultBankAccountId: integer('default_bank_account_id'),
  overtimeRateType: varchar('overtime_rate_type', { length: 50 }),
  overtimeOverrideRate: decimal('overtime_override_rate', { precision: 10, scale: 2 }),
  clientMatterId: varchar('client_matter_id', { length: 100 }),
  flatFeeType: varchar('flat_fee_type', { length: 50 }),
  hideTimeOnInvoiceDefault: boolean('hide_time_on_invoice_default'),
  hideExpenseOnInvoiceDefault: boolean('hide_expense_on_invoice_default'),
  allowABACodes: boolean('allow_aba_codes'),
  invoiceTaxLaborRate: decimal('invoice_tax_labor_rate', { precision: 5, scale: 2 }),
  invoiceTax2LaborRate: decimal('invoice_tax2_labor_rate', { precision: 5, scale: 2 }),
  invoiceTaxExpensesRate: decimal('invoice_tax_expenses_rate', { precision: 5, scale: 2 }),
  invoiceTax2ExpensesRate: decimal('invoice_tax2_expenses_rate', { precision: 5, scale: 2 }),
  minimumTrustBalance: decimal('minimum_trust_balance', { precision: 10, scale: 2 }),
  lateFeeFlat: decimal('late_fee_flat', { precision: 10, scale: 2 }),
  lateFeeRate: decimal('late_fee_rate', { precision: 5, scale: 2 }),
  lateFeeGraceDays: integer('late_fee_grace_days'),
  email: varchar('email', { length: 255 }),
  startDate: timestamp('start_date')
});

export const b4t_clientnote = pgTable('b4t_clientnote', {
  noteId: integer('note_id').primaryKey(),
  createdDate: timestamp('created_date'),
  createdById: integer('created_by_id'),
  createdBy: varchar('created_by', { length: 255 }),
  internalClientId: integer('internal_client_id'),
  clientId: varchar('client_id', { length: 50 }),
  clientName: varchar('client_name', { length: 255 }),
  noteSubject: varchar('note_subject', { length: 500 }),
  noteText: text('note_text'),
});

export const b4t_invoices = pgTable('b4t_invoices', {
  id: serial('id').primaryKey(),
  invoiceId: integer('invoice_id'),
  internalInvoiceId: integer('internal_invoice_id').notNull(),
  invoiceBatchId: integer('invoice_batch_id'),
  clientId: varchar('client_id', { length: 50 }),
  internalClientId: integer('internal_client_id'),
  clientName: varchar('client_name', { length: 255 }),
  projectId: varchar('project_id', { length: 50 }),
  internalProjectId: integer('internal_project_id'),
  projectName: varchar('project_name', { length: 255 }),
  status: varchar('status', { length: 50 }),
  createdDate: timestamp('created_date'),
  invoiceDate: timestamp('invoice_date'),
  invoiceDesc: text('invoice_desc'),
  invoiceNotes: text('invoice_notes'),
  invoiceTermType: varchar('invoice_term_type', { length: 50 }),
  invoiceDiscountType: varchar('invoice_discount_type', { length: 50 }),
  applyDiscountTo: varchar('apply_discount_to', { length: 50 }),
  invoiceDiscountAmount: decimal('invoice_discount_amount', { precision: 15, scale: 2 }),
  laborTaxRatePCT: decimal('labor_tax_rate_pct', { precision: 5, scale: 2 }),
  expenseTaxRatePCT: decimal('expense_tax_rate_pct', { precision: 5, scale: 2 }),
  secondaryTaxLabor: decimal('secondary_tax_labor', { precision: 5, scale: 2 }),
  secondaryTaxExpenses: decimal('secondary_tax_expenses', { precision: 5, scale: 2 }),
  invoiceSummary: text('invoice_summary'),
  showLaborSummary: boolean('show_labor_summary'),
  showExpSummary: boolean('show_exp_summary'),
  writeUpDownAmountLabor: decimal('write_up_down_amount_labor', { precision: 15, scale: 2 }),
  writeUpDownAmountExp: decimal('write_up_down_amount_exp', { precision: 15, scale: 2 }),
  invoiceExpenseTotalPreTax: decimal('invoice_expense_total_pre_tax', { precision: 15, scale: 2 }),
  invoiceLaborTotalPreTax: decimal('invoice_labor_total_pre_tax', { precision: 15, scale: 2 }),
  invoiceProjectExpenseTotalPreTax: decimal('invoice_project_expense_total_pre_tax', { precision: 15, scale: 2 }),
  invoiceProjectLaborTotalPreTax: decimal('invoice_project_labor_total_pre_tax', { precision: 15, scale: 2 }),
  invoiceProjectTotalPreTax: decimal('invoice_project_total_pre_tax', { precision: 15, scale: 2 }),
  invoiceTotal: decimal('invoice_total', { precision: 15, scale: 2 }),
  qbSyncDate: timestamp('qb_sync_date'),
  iifExportDate: timestamp('iif_export_date'),
  paidStatus: varchar('paid_status', { length: 50 }),
});

export const b4t_expenses = pgTable('b4t_expenses', {
  expenseId: integer('expense_id').primaryKey(),
  internalClientId: integer('internal_client_id'),
  clientId: varchar('client_id', { length: 50 }),
  clientName: varchar('client_name', { length: 255 }),
  internalProjectId: integer('internal_project_id'),
  projectId: varchar('project_id', { length: 50 }),
  projectName: varchar('project_name', { length: 255 }),
  userId: integer('user_id'),
  userName: varchar('user_name', { length: 255 }),
  expenseType: varchar('expense_type', { length: 100 }),
  costPrice: decimal('cost_price', { precision: 15, scale: 2 }),
  sellPrice: decimal('sell_price', { precision: 15, scale: 2 }),
  unitPrice: decimal('unit_price', { precision: 15, scale: 2 }),
  reimburse: boolean('reimburse'),
  excludeFromInvoice: boolean('exclude_from_invoice'),
  taxable: boolean('taxable'),
  expenseDate: timestamp('expense_date'),
  createdDate: timestamp('created_date'),
  quantity: integer('quantity'),
  invoiceId: integer('invoice_id'),
  invoiceBatchId: integer('invoice_batch_id'),
  invoiceAdjustedAmount: decimal('invoice_adjusted_amount', { precision: 15, scale: 2 }),
  billingStatus: varchar('billing_status', { length: 50 }),
  description: text('description'),
  expenseCode: varchar('expense_code', { length: 50 }),
});

export const b4t_payments = pgTable('b4t_payments', {
  paymentId: integer('payment_id').primaryKey(),
  internalClientId: integer('internal_client_id'),
  clientId: varchar('client_id', { length: 50 }),
  clientName: varchar('client_name', { length: 255 }),
  internalProjectId: integer('internal_project_id'),
  projectId: varchar('project_id', { length: 50 }),
  projectName: varchar('project_name', { length: 255 }),
  pmtType: varchar('pmt_type', { length: 50 }),
  pmtMethod: varchar('pmt_method', { length: 50 }),
  checkNumber: varchar('check_number', { length: 100 }),
  pmtDate: timestamp('pmt_date'),
  entryDate: timestamp('entry_date'),
  pmtAmount: decimal('pmt_amount', { precision: 15, scale: 2 }),
  privateNotes: text('private_notes'),
  publicNotes: text('public_notes'),
  trustAccountingId: integer('trust_accounting_id'),
  createdById: integer('created_by_id'),
  createdByName: varchar('created_by_name', { length: 255 }),
  updatedById: integer('updated_by_id'),
  updatedByName: varchar('updated_by_name', { length: 255 }),
  qbSyncDate: timestamp('qb_sync_date'),
  isAppliedOverride: boolean('is_applied_override'),
  processorSource: varchar('processor_source', { length: 100 }),
  retainerRequestId: integer('retainer_request_id'),
  bankAccountId: integer('bank_account_id'),
  paymentPlanId: integer('payment_plan_id'),
  scheduledPaymentId: integer('scheduled_payment_id'),
  balanceAdjustment: boolean('balance_adjustment'),
  debit: decimal('debit', { precision: 15, scale: 2 }),
  credit: decimal('credit', { precision: 15, scale: 2 }),
});

export const b4t_timeentries = pgTable('b4t_timeentries', {
  timeEntryId: integer('time_entry_id').primaryKey(),
  internalClientId: integer('internal_client_id'),
  clientId: varchar('client_id', { length: 50 }),
  clientName: varchar('client_name', { length: 255 }),
  internalProjectId: integer('internal_project_id'),
  projectId: varchar('project_id', { length: 50 }),
  projectName: varchar('project_name', { length: 255 }),
  locationId: integer('location_id'),
  locationName: varchar('location_name', { length: 255 }),
  userId: integer('user_id'),
  userName: varchar('user_name', { length: 255 }),
  internalTime: varchar('internal_time', { length: 50 }),
  activityType: varchar('activity_type', { length: 100 }),
  status: varchar('status', { length: 50 }),
  billTime: decimal('bill_time', { precision: 8, scale: 2 }),
  laborTime: decimal('labor_time', { precision: 8, scale: 2 }),
  travelTime: decimal('travel_time', { precision: 8, scale: 2 }),
  createdDate: timestamp('created_date'),
  createdById: integer('created_by_id'),
  entryDate: timestamp('entry_date'),
  endTime: varchar('end_time', { length: 20 }),
  privateDescription: text('private_description'),
  publicDescription: text('public_description'),
  billable: boolean('billable'),
  reasonForOverrideNumOfBillableHours: varchar('reason_for_override_num_of_billable_hours', { length: 255 }),
  invoiceBatchId: integer('invoice_batch_id'),
  lockedRate: decimal('locked_rate', { precision: 10, scale: 2 }),
  overrideRate: decimal('override_rate', { precision: 10, scale: 2 }),
  flatFeeFlag: boolean('flat_fee_flag'),
  flatFeeAmount: decimal('flat_fee_amount', { precision: 15, scale: 2 }),
  percentageFlag: boolean('percentage_flag'),
  settlementAmount: decimal('settlement_amount', { precision: 15, scale: 2 }),
  hourlyFlag: boolean('hourly_flag'),
  excludeFromInvoice: boolean('exclude_from_invoice'),
  overtimeFlag: boolean('overtime_flag'),
  litigationCode: varchar('litigation_code', { length: 50 }),
  activityCode: varchar('activity_code', { length: 50 }),
  invoiceAdjustedAmount: decimal('invoice_adjusted_amount', { precision: 15, scale: 2 }),
  invoiceId: integer('invoice_id'),
  doubletimeRateFlag: boolean('doubletime_rate_flag'),
  approvalStatus: varchar('approval_status', { length: 50 }),
  calculatedRate: decimal('calculated_rate', { precision: 15, scale: 2 }),
  calculatedAmount: decimal('calculated_amount', { precision: 15, scale: 2 }),
  calculatedRateAssumeBillable: decimal('calculated_rate_assume_billable', { precision: 15, scale: 2 }),
  calculatedAmountAssumeBillable: decimal('calculated_amount_assume_billable', { precision: 15, scale: 2 }),
  calculatedPayableRate: decimal('calculated_payable_rate', { precision: 15, scale: 2 }),
  calculatedAmountNonAdjusted: decimal('calculated_amount_non_adjusted', { precision: 15, scale: 2 }),
  dateUpdated: timestamp('date_updated'),
  updatedBy: varchar('updated_by', { length: 255 }),
});

export const b4t_trustaccounting = pgTable('b4t_trustaccounting', {
  trustAccountingId: integer('trust_accounting_id').primaryKey(),
  payIn: boolean('pay_in'),
  dateCreated: timestamp('date_created'),
  dateTransaction: timestamp('date_transaction'),
  checkNumber: varchar('check_number', { length: 50 }),
  transactionDesc: text('transaction_desc'),
  description: text('description'),
  internalProjectId: integer('internal_project_id'),
  projectId: varchar('project_id', { length: 50 }),
  projectName: varchar('project_name', { length: 255 }),
  internalClientId: integer('internal_client_id'),
  clientId: varchar('client_id', { length: 50 }),
  clientName: varchar('client_name', { length: 255 }),
  amount: decimal('amount', { precision: 15, scale: 2 }),
  bankAccountId: integer('bank_account_id'),
  bankName: varchar('bank_name', { length: 255 }),
  payment: boolean('payment'),
  transfer: boolean('transfer'),
  transferPairId: integer('transfer_pair_id'),
  dateCleared: timestamp('date_cleared'),
  checkVoided: boolean('check_voided'),
  checkVoidDate: timestamp('check_void_date'),
  checkVoidReason: text('check_void_reason'),
  retainerRequestId: integer('retainer_request_id'),
  paymentPlanId: integer('payment_plan_id'),
  scheduledPaymentId: integer('scheduled_payment_id'),
});

export const b4t_paymentsapplied = pgTable('b4t_paymentsapplied', {
  id: integer('id').primaryKey(),
  paymentId: integer('payment_id'),
  invoiceId: integer('invoice_id'),
  amountApplied: decimal('amount_applied', { precision: 15, scale: 2 }),
  dateApplied: timestamp('date_applied'),
  dateCreated: timestamp('date_created'),
});

export const tbl_clientlinks_googledrive_b4t = pgTable('tbl_clientlinks_googledrive_b4t', {
  id: serial('id').primaryKey(),
  internalClientId: integer('internal_client_id').notNull().unique(),
  clientName: varchar('client_name', { length: 255 }),
  assignedToName: varchar('assigned_to_name', { length: 255 }),
  folderName: varchar('folder_name', { length: 500 }),
  driveUrl: text('drive_url'),
  b4tUrl: varchar('b4t_url', { length: 500 }),
  b4tDisplayText: varchar('b4t_display_text', { length: 255 }),
  lastUpdated: timestamp('last_updated').defaultNow(),
  createdDate: timestamp('created_date').defaultNow(),
  matchType: varchar('match_type', { length: 50 }).default('MANUAL'),
  isActive: boolean('is_active').default(true),
});

export const tbl_tech_reports = pgTable('tbl_tech_reports', {
  id: serial('id').primaryKey(),
  reportName: varchar('report_name', { length: 255 }),
  purpose: varchar('purpose', { length: 255 }),
  criteria: varchar('criteria', { length: 255 }),
  frequency: varchar('frequency', { length: 50 }).notNull(),
  department: varchar('department', { length: 100 }),
  path: varchar('path', { length: 255 }),
  recipientB4tId: integer('recipient_b4t_id'),
  recipients: varchar('recipients', { length: 255 }),
  funnelChat: varchar('funnel_chat', { length: 255 }),
  productionSharedDriveLink: varchar('production_shared_drive_link', { length: 512 })
});
